# Generated by Django 3.1.4 on 2020-12-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201226_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approve_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ES', 'Ex_Student'), ('S', 'Student'), ('T', 'Teacher'), ('P', 'Parent'), ('St', 'Staff'), ('G', 'Guest'), ('CC', 'Current_Committee')], default='G', max_length=3),
        ),
    ]
