# Generated by Django 3.1.4 on 2020-12-29 20:20

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201230_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[user.utils.validators_phone_number]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ES', 'Ex Student'), ('S', 'Student'), ('T', 'Teacher'), ('P', 'Parent'), ('St', 'Staff'), ('G', 'Guest'), ('CC', 'Current Committee'), ('A', 'Admin'), ('E', 'Editor'), ('SV', 'Supervisor')], default='G', max_length=3),
        ),
    ]
